// ==UserScript==
// @name         DeepSeek Web Passive Research Observer
// @namespace    local.deepseek.research
// @version      1.0.0
// @description  Passive local observer for authorized DeepSeek Web research
// @match        https://chat.deepseek.com/*
// @run-at       document-start
// @grant        none
// ==/UserScript==

(() => {
  'use strict';
  if (globalThis.__DeepSeekObserverInstalled) return;
  globalThis.__DeepSeekObserverInstalled = true;

  const SENSITIVE = /(authorization|proxy-authorization|cookie|set-cookie|token|access[_-]?token|refresh[_-]?token|id[_-]?token|csrf|xsrf|session|secret|password|api[_-]?key|apikey|credential)/i;
  const SECRETISH = /(?:eyJ[A-Za-z0-9_-]{20,}|sk-[A-Za-z0-9_-]{12,}|[A-Za-z0-9+/_-]{48,}={0,2})/;
  const MAX_BODY = 65536, MAX_EVENTS = 100, MAX_STREAM_BYTES = 131072;
  const now = () => new Date().toISOString();
  const state = { recording:true, paused:false, seq:0, epSeq:0, streamSeq:0, scenarioSeq:0, current:null,
    ops:[], streams:[], files:[], markers:[], scenarios:[], endpoints:new Map(), resources:[], frontend:[], storage:null,
    warnings:[], originals:{}, listeners:[], config:{synthetic:false}, ui:null, timer:null };

  const active = () => state.recording && !state.paused;
  const sensitive = k => SENSITIVE.test(String(k));
  const testText = v => typeof v === 'string' && /(?:CAPTURE_|PHASE[0-9]_FILE_TEST|capture_)/i.test(v);
  const secretish = v => typeof v === 'string' && SECRETISH.test(v);
  const url = input => { try { const u=new URL(input, location.href); const path=u.pathname.split('/').map(s=>/^(?:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}|[A-Za-z0-9_-]{24,})$/i.test(s)?'<REDACTED_PATH_SEGMENT>':s).join('/'); const q=[];u.searchParams.forEach((_,k)=>q.push(sensitive(k)?'<REDACTED_QUERY_KEY>':k));return {origin:u.origin,path,query_keys:[...new Set(q)]}; } catch(_) {return {origin:'UNKNOWN',path:'UNKNOWN',query_keys:[]};} };
  const type = v => v===null?'null':Array.isArray(v)?'array':v instanceof Blob?'blob':v instanceof ArrayBuffer?'binary':typeof v;
  const shape = (v,d=0) => { if(d>4)return {type:'truncated_depth'}; if(v===null)return {type:'null'}; if(Array.isArray(v))return {type:'array',length:v.length,items:v.length?shape(v[0],d+1):{type:'unknown'}}; if(typeof v!=='object')return {type:typeof v,length:typeof v==='string'?v.length:undefined}; const keys={};Object.keys(v).slice(0,100).forEach(k=>keys[sensitive(k)?'<REDACTED_FIELD>':k]=sensitive(k)?{type:'<REDACTED>'}:shape(v[k],d+1));return {type:'object',keys}; };
  const bodyShape = b => { if(b==null)return {classification:'none',schema:null};if(b instanceof FormData){const fields=[];b.forEach((v,k)=>fields.push({field_name:sensitive(k)?'<REDACTED_FIELD>':k,type:v instanceof File?'file':type(v),size:v instanceof File?v.size:undefined}));return {classification:'multipart',schema:{type:'form-data',fields}}}if(b instanceof URLSearchParams)return {classification:'form-urlencoded',schema:{type:'url-search-params',keys:[...b.keys()].map(k=>sensitive(k)?'<REDACTED_FIELD>':k)}};if(typeof b==='string'){try{return {classification:'json',schema:shape(JSON.parse(b))}}catch(_){return {classification:'text',schema:{type:'string',length:b.length,value:state.config.synthetic&&testText(b)?b.slice(0,500):undefined}}}}return {classification:b instanceof Blob||b instanceof ArrayBuffer?'binary':'unknown',schema:{type:type(b),size:b&&(+b.size||+b.byteLength)||undefined}}; };
  const headerNames = h => {const names=[],red=[];try{const add=k=>(sensitive(k)?red:names).push(String(k).toLowerCase());if(h instanceof Headers)h.forEach((_,k)=>add(k));else if(Array.isArray(h))h.forEach(x=>add(x[0]));else if(h&&typeof h==='object')Object.keys(h).forEach(add)}catch(_){}return [...new Set(names)].concat(red.length?['<REDACTED_AUTH_HEADER>']:[])};
  const ct = h => {try{return h&&h.get&&h.get('content-type')||'UNKNOWN'}catch(_){return'UNKNOWN'}};
  const scenario = () => state.current&&state.current.id||null;
  const register = op => { if(!active())return null;op.id=`OP-${String(++state.seq).padStart(4,'0')}`;op.timestamp=now();op.scenario=scenario();op.confidence='OBSERVED';state.ops.push(op);const key=`${op.method}|${op.origin}|${op.path}`;let ep=state.endpoints.get(key);if(!ep){ep={endpoint_id:`EP-${String(++state.epSeq).padStart(3,'0')}`,method:op.method,origin:op.origin,path:op.path,observed_count:0,scenarios:[],request_schema:null,response_schema:null,streaming:{status:'UNKNOWN'},confidence:'OBSERVED'};state.endpoints.set(key,ep)}ep.observed_count++;if(op.scenario&&!ep.scenarios.includes(op.scenario))ep.scenarios.push(op.scenario);if(op.request_body&&!ep.request_schema)ep.request_schema=op.request_body.schema;op.endpoint_id=ep.endpoint_id;return op; };
  const update = (op,p) => {if(!op)return;Object.assign(op,p);const ep=[...state.endpoints.values()].find(e=>e.endpoint_id===op.endpoint_id);if(ep){if(op.response_schema)ep.response_schema=op.response_schema;if(op.streaming_candidate)ep.streaming={status:'OBSERVED',transport:op.transport};}};
  const parseSSE = (text, rec, started) => {text.split(/\r?\n\r?\n/).slice(0,40).forEach(block=>{if(rec.events.length>=MAX_EVENTS)return;const lines=block.split(/\r?\n/),ev=lines.find(x=>x.startsWith('event:')),data=lines.filter(x=>x.startsWith('data:')).map(x=>x.slice(5).trim()).join('\n');if(!data)return;if(data==='[DONE]'){rec.completion_indicator='data_DONE';return}let s;try{s=shape(JSON.parse(data))}catch(_){s={type:'string',length:data.length}}rec.events.push({sequence:rec.events.length+1,timestamp:now(),event_type:ev?ev.slice(6).trim():'UNKNOWN',data_type:s.type,schema:s,size:data.length,timing_ms:Math.round(performance.now()-started)});}); };
  const attachStreamProgress = (xhr, op, start) => {let seen=0,rec=null;const progress=()=>{if(!active())return;let t;try{t=xhr.responseText}catch(_){if(rec)rec.access='NOT_OBSERVABLE';return}if(typeof t!=='string'||t.length<=seen)return;const d=t.slice(seen,Math.min(t.length,seen+MAX_BODY));seen=t.length;if(!rec){let c='UNKNOWN';try{c=xhr.getResponseHeader('content-type')||c}catch(_){}rec={stream_id:`S-${String(++state.streamSeq).padStart(3,'0')}`,scenario:op&&op.scenario||null,operation_id:op&&op.id||null,timestamp:now(),path:op&&op.path||'UNKNOWN',status:xhr.status||null,content_type:c,transport:'xhr-progress',start_ms:Math.round(performance.now()-start),end_ms:null,duration_ms:null,chunks:0,chunk_sizes:[],framing:'UNKNOWN',events:[],completion_indicator:'UNKNOWN',error_indicator:'UNKNOWN',raw_payloads_stored:false};state.streams.push(rec)}rec.chunks++;rec.chunk_sizes.push(d.length);if(/text\/event-stream/i.test(rec.content_type)||/(^|\n)(event|data):/m.test(d))rec.framing='SSE_LIKE_OBSERVED';parseSSE(d,rec,start);};xhr.addEventListener('progress',progress);xhr.addEventListener('abort',()=>{if(rec)rec.error_indicator='xhr_abort'});xhr.addEventListener('error',()=>{if(rec)rec.error_indicator='xhr_error'});xhr.addEventListener('loadend',()=>{if(rec){rec.end_ms=Math.round(performance.now()-start);rec.duration_ms=rec.end_ms;if(rec.completion_indicator==='UNKNOWN')rec.completion_indicator='xhr_loadend'}}); };
  const install = () => {
    if(state.originals.fetch)return;
    state.originals.fetch=window.fetch;window.fetch=function(input,init){const r=input instanceof Request?input:null,u=url(r?r.url:input),method=String(init&&init.method||r&&r.method||'GET').toUpperCase(),op=register({transport:'fetch',method,origin:u.origin,path:u.path,query_keys:u.query_keys,request_headers:headerNames(init&&init.headers||r&&r.headers),request_body:bodyShape(init&&Object.prototype.hasOwnProperty.call(init,'body')?init.body:null),status:null,content_type:'UNKNOWN',duration_ms:null,streaming_candidate:false});const start=performance.now(),out=state.originals.fetch.apply(this,arguments);Promise.resolve(out).then(res=>{const c=ct(res.headers);update(op,{status:res.status,content_type:c,duration_ms:Math.round(performance.now()-start),streaming_candidate:/event-stream/i.test(c)});if(active()&&res.body&&res.body.getReader){let clone;try{clone=res.clone()}catch(_){return}const reader=clone.body.getReader(),rec={stream_id:`S-${String(++state.streamSeq).padStart(3,'0')}`,scenario:op&&op.scenario||null,operation_id:op&&op.id||null,timestamp:now(),path:u.path,status:res.status,content_type:c,transport:'fetch-clone',chunks:0,chunk_sizes:[],framing:'UNKNOWN',events:[],completion_indicator:'UNKNOWN',error_indicator:'UNKNOWN',raw_payloads_stored:false};(async()=>{let total=0,text='',dec=new TextDecoder();try{while(total<MAX_STREAM_BYTES&&rec.chunks<MAX_EVENTS){const x=await reader.read();if(x.done){rec.completion_indicator='reader_done';break}rec.chunks++;total+=x.value.byteLength;rec.chunk_sizes.push(x.value.byteLength);text+=dec.decode(x.value,{stream:true})}if(/event-stream/i.test(c)||/(^|\n)(event|data):/m.test(text)){rec.framing='SSE_LIKE_OBSERVED';parseSSE(text,rec,start)}state.streams.push(rec)}catch(_){rec.error_indicator='clone_reader_error';state.streams.push(rec)}finally{try{reader.cancel()}catch(_){}}})();}});return out;};
    const X=window.XMLHttpRequest;state.originals.X=X;state.originals.xopen=X.prototype.open;state.originals.xsend=X.prototype.send;state.originals.xset=X.prototype.setRequestHeader;X.prototype.open=function(m,u){this.__dso={method:String(m||'GET').toUpperCase(),u:url(u),headers:[]};return state.originals.xopen.apply(this,arguments)};X.prototype.setRequestHeader=function(k){if(this.__dso)this.__dso.headers.push(k);return state.originals.xset.apply(this,arguments)};X.prototype.send=function(b){const x=this.__dso||{method:'UNKNOWN',u:url(''),headers:[]},start=performance.now(),op=register({transport:'xhr',method:x.method,origin:x.u.origin,path:x.u.path,query_keys:x.u.query_keys,request_headers:headerNames(x.headers.map(k=>[k,''])),request_body:bodyShape(b),status:null,content_type:'UNKNOWN',duration_ms:null,streaming_candidate:false,lifecycle:['OPENED','SENT']});const observe=()=>{let c='UNKNOWN';try{c=this.getResponseHeader('content-type')||c}catch(_){}const life=this.readyState===2?'HEADERS_RECEIVED':this.readyState===3?'LOADING':this.readyState===4?'DONE':null;if(life)update(op,{status:this.status||null,content_type:c,duration_ms:Math.round(performance.now()-start),streaming_candidate:/event-stream/i.test(c)||this.readyState===3,lifecycle:(op&&op.lifecycle||[]).concat(life)});if(this.readyState===4&&/json/i.test(c)&&typeof this.responseText==='string'&&this.responseText.length<=MAX_BODY){try{update(op,{response_schema:shape(JSON.parse(this.responseText))})}catch(_){}}};this.addEventListener('readystatechange',observe);this.addEventListener('error',()=>update(op,{error:'xhr_error'}));this.addEventListener('abort',()=>update(op,{error:'xhr_abort'}));attachStreamProgress(this,op,start);return state.originals.xsend.apply(this,arguments)};
    if(window.EventSource){const E=window.EventSource;state.originals.EventSource=E;function ObsES(u,c){const q=url(u),es=new E(u,c),op=register({transport:'eventsource',method:'GET',origin:q.origin,path:q.path,query_keys:q.query_keys,status:null,content_type:'text/event-stream',duration_ms:null,streaming_candidate:true});const rec={stream_id:`S-${String(++state.streamSeq).padStart(3,'0')}`,scenario:op&&op.scenario||null,operation_id:op&&op.id||null,timestamp:now(),path:q.path,transport:'eventsource',chunks:0,chunk_sizes:[],framing:'SSE_OBSERVED',events:[],completion_indicator:'UNKNOWN',error_indicator:'UNKNOWN',raw_payloads_stored:false};es.addEventListener('open',()=>update(op,{status:200}));es.addEventListener('message',e=>{if(!active())return;const d=String(e.data||'');rec.chunks++;rec.chunk_sizes.push(d.length);let s;try{s=shape(JSON.parse(d))}catch(_){s={type:'string',length:d.length}}if(rec.events.length<MAX_EVENTS)rec.events.push({sequence:rec.events.length+1,timestamp:now(),event_type:'message',data_type:s.type,schema:s,size:d.length})});es.addEventListener('error',()=>{rec.error_indicator='eventsource_error';state.streams.push(rec)});return es}ObsES.prototype=E.prototype;Object.setPrototypeOf(ObsES,E);window.EventSource=ObsES;}
    if(window.WebSocket){const W=window.WebSocket;state.originals.WebSocket=W;function ObsWS(u,p){const q=url(u),ws=p===undefined?new W(u):new W(u,p),op=register({transport:'websocket',method:'CONNECT',origin:q.origin,path:q.path,query_keys:q.query_keys,status:null,content_type:'websocket',duration_ms:null,streaming_candidate:true});const rec={stream_id:`S-${String(++state.streamSeq).padStart(3,'0')}`,scenario:op&&op.scenario||null,operation_id:op&&op.id||null,timestamp:now(),path:q.path,transport:'websocket',chunks:0,chunk_sizes:[],framing:'message_boundaries_observed',events:[],completion_indicator:'UNKNOWN',error_indicator:'UNKNOWN',raw_payloads_stored:false};ws.addEventListener('open',()=>update(op,{status:101}));ws.addEventListener('message',e=>{if(!active())return;const d=e.data,n=typeof d==='string'?d.length:d&&(+d.size||+d.byteLength)||0;rec.chunks++;rec.chunk_sizes.push(n);let s;if(typeof d==='string'){try{s=shape(JSON.parse(d))}catch(_){s={type:'string',length:n}}}else s={type:'binary',size:n};if(rec.events.length<MAX_EVENTS)rec.events.push({sequence:rec.events.length+1,timestamp:now(),event_type:'message',data_type:s.type,schema:s,size:n})});ws.addEventListener('close',e=>{rec.completion_indicator='close';rec.close_code=e.code;state.streams.push(rec)});ws.addEventListener('error',()=>rec.error_indicator='websocket_error');return ws}ObsWS.prototype=W.prototype;Object.setPrototypeOf(ObsWS,W);window.WebSocket=ObsWS;}
  };
  const classifyKey=k=>sensitive(k)?'AUTHENTICATION_RELATED':/(theme|locale|language|banner|ui)/i.test(k)?'UI_PREFERENCE':/(thinking|search|feature|model|config)/i.test(k)?'FEATURE_CONFIG':/(history|message|conversation)/i.test(k)?'HISTORY':/(apm|tea|log|telemetry)/i.test(k)?'TELEMETRY':'UNKNOWN';
  const inspectStorage=async()=>{const web=(s,name)=>{const entries=[];try{for(let i=0;i<s.length;i++){const k=s.key(i),v=s.getItem(k),red=sensitive(k)||secretish(v);let sch=null;if(!red&&v&&v.length<8192){try{sch=shape(JSON.parse(v))}catch(_){}}entries.push({key:red?'auth-related-key':k,classification:classifyKey(k),type:sch?'json-string':'string',size:v?v.length:0,schema:sch,value:red?'<REDACTED>':undefined})}}catch(e){return{status:'UNKNOWN',error:e.name}}return{status:'OBSERVED',mechanism:name,entries}};
    const idb={status:'UNKNOWN',databases:[]};try{if(indexedDB.databases){const dbs=await indexedDB.databases();idb.status='OBSERVED';await Promise.all(dbs.map(i=>new Promise(done=>{if(!i.name){done();return}const r=indexedDB.open(i.name);r.onerror=()=>{idb.databases.push({name:i.name,status:'UNREADABLE'});done()};r.onsuccess=()=>{const db=r.result,stores=Array.from(db.objectStoreNames).map(n=>{const st=db.transaction(n,'readonly').objectStore(n);return{name:n,keyPath:st.keyPath||null,autoIncrement:!!st.autoIncrement,indexes:Array.from(st.indexNames),record_count:'NOT_READ'}});idb.databases.push({name:db.name,version:db.version,stores});db.close();done()}})));}}catch(e){idb.error=e.name}
    const cache={status:'UNKNOWN',caches:[]};try{if(window.caches){cache.status='OBSERVED';for(const n of await caches.keys()){const c=await caches.open(n),keys=await c.keys();cache.caches.push({name:n,count:keys.length,paths:keys.slice(0,100).map(x=>url(x.url).path)})}}}catch(e){cache.error=e.name}
    const sw={status:'UNKNOWN',registrations:[]};try{if(navigator.serviceWorker){sw.status='OBSERVED';sw.registrations=(await navigator.serviceWorker.getRegistrations()).map(r=>({scope:url(r.scope).path,active:r.active&&r.active.state||'none'}))}}catch(e){sw.error=e.name}
    state.storage={timestamp:now(),localStorage:web(localStorage,'localStorage'),sessionStorage:web(sessionStorage,'sessionStorage'),indexedDB:idb,cache_storage:cache,service_workers:sw};render();return state.storage;};
  const recordFiles=e=>{if(!active())return;const fs=e.target&&e.target.files||e.dataTransfer&&e.dataTransfer.files;if(!fs)return;Array.from(fs).forEach(f=>state.files.push({status:'OBSERVED',timestamp:now(),scenario:scenario(),operation:'file_selected',filename:state.config.synthetic&&testText(f.name)?f.name:'<REDACTED_OR_TEST_FILENAME>',mime_type:f.type||'UNKNOWN',size:f.size,transport:'UNKNOWN'}));render();};
  const scanFrontend=()=>{const map=new Map(),add=(origin,path,kind,meta={})=>{const k=origin+path;if(!map.has(k))map.set(k,{status:'OBSERVED',origin,path,resource_type:kind,transfer_size:0,decoded_size:0,initiator:'UNKNOWN',matches:[]});Object.assign(map.get(k),meta)};performance.getEntriesByType('resource').forEach(e=>{const u=url(e.name);add(u.origin,u.path,e.initiatorType,{transfer_size:e.transferSize||0,decoded_size:e.decodedBodySize||0,initiator:e.initiatorType})});document.querySelectorAll('script[src],link[href]').forEach(n=>{const u=url(n.src||n.href);add(u.origin,u.path,n.tagName==='SCRIPT'?'script':'link')});const needles=['/api/v0/','chat/completion','chat_session','upload_file','fetch_files','create_pow_challenge','text/event-stream','ReadableStream','EventSource','history-message','IndexedDB','thinking_enabled','search_enabled','parent_message_id','ref_file_ids','model_type'];document.querySelectorAll('script:not([src])').forEach((n,i)=>{const t=n.textContent||'',u={origin:location.origin,path:`<inline-script-${i}>`};add(u.origin,u.path,'inline-script');needles.forEach(x=>{if(t.includes(x))map.get(u.origin+u.path).matches.push({category:x,location:'inline-script'})})});state.resources=[...map.values()];state.frontend=state.resources.filter(r=>r.matches.length);render();return state.resources;};
  const redact=v=>{if(typeof v==='string')return secretish(v)?'<REDACTED>':v;if(Array.isArray(v))return v.map(redact);if(v&&typeof v==='object'){const o={};Object.keys(v).forEach(k=>o[sensitive(k)?'<REDACTED_FIELD>':k]=sensitive(k)?'<REDACTED>':redact(v[k]));return o}return v};
  const data=level=>{const base={metadata:{observer:'DeepSeek Tampermonkey Passive Research Observer',version:'1.0.0',exported_at:now(),local_only:true,raw_payloads_stored:false},endpoint_inventory:[...state.endpoints.values()],scenario_summary:state.scenarios,stream_summary:state.streams.map(s=>({stream_id:s.stream_id,scenario:s.scenario,path:s.path,transport:s.transport,duration_ms:s.duration_ms,chunks:s.chunks,event_count:s.events.length,event_types:[...new Set(s.events.map(e=>e.event_type))],completion_indicator:s.completion_indicator,error_indicator:s.error_indicator})),storage_summary:state.storage,frontend_resource_summary:state.resources};if(level==='full')Object.assign(base,{operations:state.ops,streams:state.streams,files:state.files,markers:state.markers,frontend_analysis:state.frontend});return redact(base)};
  const validate=o=>{let hit=[];const walk=(v,p='')=>{if(typeof v==='string'&&secretish(v)&&v!=='<REDACTED>')hit.push(p);else if(Array.isArray(v))v.forEach((x,i)=>walk(x,p+'/'+i));else if(v&&typeof v==='object')Object.entries(v).forEach(([k,x])=>walk(x,p+'/'+k))};walk(o);return {ok:!hit.length,locations:hit.map(x=>'<REDACTED_LOCATION>')};};
  const download=(name,obj)=>{const check=validate(obj);if(!check.ok){alert('EXPORT BLOCKED: sensitive-looking value detected.');return false}const a=document.createElement('a'),b=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'});a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);return true};
  const crc32=a=>{let c=~0;for(let i=0;i<a.length;i++){c^=a[i];for(let j=0;j<8;j++)c=c>>>1^(c&1?0xEDB88320:0)}return~c>>>0};const u16=n=>[n&255,n>>>8&255],u32=n=>[n&255,n>>>8&255,n>>>16&255,n>>>24&255];
  const zip=files=>{const enc=new TextEncoder(),parts=[],central=[];let off=0;for(const [name,obj] of Object.entries(files)){const n=enc.encode(name),b=enc.encode(typeof obj==='string'?obj:JSON.stringify(obj,null,2)),c=crc32(b),local=new Uint8Array([80,75,3,4,20,0,0,0,0,0,0,0,0,0,...u32(c),...u32(b.length),...u32(b.length),...u16(n.length),0,0,...n,...b]);parts.push(local);central.push(new Uint8Array([80,75,1,2,20,0,20,0,0,0,0,0,0,0,...u32(c),...u32(b.length),...u32(b.length),...u16(n.length),0,0,0,0,0,0,0,0,0,0,...u32(off),...n]));off+=local.length}const clen=central.reduce((n,x)=>n+x.length,0),end=new Uint8Array([80,75,5,6,0,0,0,0,...u16(files?Object.keys(files).length:0),...u16(Object.keys(files).length),...u32(clen),...u32(off),0,0]);return new Blob([...parts,...central,end],{type:'application/zip'})};
  const mark=(kind='ACTION')=>{const m={timestamp:now(),scenario:scenario(),type:'USER_ACTION',label:kind};state.markers.push(m);return m};
  const begin=label=>{if(state.current)end();const s={id:`SCENARIO-${String(++state.scenarioSeq).padStart(3,'0')}`,label,started_at:now(),ended_at:null,operation_ids:[]};state.current=s;state.scenarios.push(s);mark(label+'_START');render()};const end=()=>{if(!state.current)return;mark(state.current.label+'_END');state.current.ended_at=now();state.current=null;render()};
  const summary=()=>({endpoints:state.endpoints.size,operations:state.ops.length,streams:state.streams.length,files:state.files.length,resources:state.resources.length,storage_keys:state.storage&&state.storage.localStorage.entries.length||0,indexeddb:state.storage&&state.storage.indexedDB.databases.length||0});
  const row=(a)=>a.map(x=>`<tr>${x.map(y=>`<td>${String(y??'').replace(/[<>&]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;'}[c]))}</td>`).join('')}</tr>`).join('');
  const render=()=>{const p=state.ui;if(!p)return;const s=summary();p.$('#status').textContent=state.recording?(state.paused?'● PAUSED':'● RECORDING'):'● STOPPED';p.$('#counts').textContent=`Requests ${s.operations} · Streams ${s.streams} · IndexedDB ${s.indexeddb} DB · Storage ${s.storage_keys} keys · Files ${s.files} · Resources ${s.resources}`;const tab=p.tab;
    let html='';if(tab==='Overview')html=`<b>Local-only passive observer</b><p>${JSON.stringify(s)}</p><p>Current scenario: ${state.current?state.current.label:'none'}</p>`;
    if(tab==='Requests')html=`<table><tr><th>Time</th><th>Scenario</th><th>Method</th><th>Path</th><th>Status</th><th>Stream</th></tr>${row(state.ops.slice(-100).map(o=>[o.timestamp.slice(11,19),o.scenario||'',o.method,o.path,o.status||'',o.streaming_candidate?'yes':'']))}</table>`;
    if(tab==='Streams')html=`<table><tr><th>ID</th><th>Scenario</th><th>Duration</th><th>Chunks</th><th>Events</th><th>Framing</th></tr>${row(state.streams.map(x=>[x.stream_id,x.scenario||'',x.duration_ms||'',x.chunks,x.events.length,x.framing]))}</table>`;
    if(tab==='Files')html=`<pre>${JSON.stringify(state.files,null,2)}</pre>`;
    if(tab==='Storage')html=`<button data-act="inspect">Inspect storage</button><pre>${state.storage?JSON.stringify(state.storage,null,2):'Not inspected'}</pre>`;
    if(tab==='Frontend')html=`<button data-act="frontend">Refresh resource inventory</button><table><tr><th>Type</th><th>Origin</th><th>Path</th><th>Bytes</th><th>Matches</th></tr>${row(state.resources.map(x=>[x.resource_type,x.origin,x.path,x.decoded_size,x.matches.map(m=>m.category).join(',')]))}</table><p>External bundle source text is NOT read/fetched by this observer; only loaded-resource metadata and inline-script string matches are shown.</p>`;
    if(tab==='Scenarios')html=`<pre>${JSON.stringify(state.scenarios,null,2)}\nMarkers:\n${JSON.stringify(state.markers,null,2)}</pre>`;
    if(tab==='Export')html=`<button data-act="validate">Validate redaction</button> <button data-act="summary">Export summary JSON</button> <button data-act="full">Export full sanitized JSON</button> <button data-act="zip">Export ZIP package</button><p>Synthetic test payloads are ${state.config.synthetic?'ON':'OFF'}.</p>`;
    p.$('#body').innerHTML=html;};
  const ui=()=>{const host=document.createElement('div');host.id='deepseek-observer-host';host.style.cssText='position:fixed;top:16px;right:16px;z-index:2147483647';const shadow=host.attachShadow({mode:'closed'}),tabs=['Overview','Requests','Streams','Files','Storage','Frontend','Scenarios','Export'];shadow.innerHTML=`<style>:host{all:initial}#p{width:420px;background:#101827;color:#e5e7eb;border:1px solid #64748b;border-radius:10px;font:12px/1.35 system-ui;box-shadow:0 10px 30px #0008}#head{padding:9px;cursor:move;background:#172554;font-weight:700;display:flex;justify-content:space-between}#counts,#status{padding:4px 9px;color:#cbd5e1}.bar{padding:6px 8px;border-top:1px solid #334155}.bar button,select{font:inherit;margin:2px;padding:4px;background:#1e293b;color:#fff;border:1px solid #64748b;border-radius:4px}.tabs{display:flex;flex-wrap:wrap}.tab{font-size:11px}#body{max-height:310px;overflow:auto;padding:8px}table{border-collapse:collapse;width:100%;font-size:10px}td,th{border:1px solid #334155;padding:3px;max-width:110px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}pre{white-space:pre-wrap;word-break:break-word;font-size:10px}.min #body,.min .bar,.min .tabs{display:none}</style><div id="p"><div id="head">DeepSeek Observer <span id="status"></span><span><button data-act="min">−</button><button data-act="close">×</button></span></div><div id="counts"></div><div class="bar"><select id="scenario">${['NORMAL_MESSAGE','THINKING_MESSAGE','SEARCH_MESSAGE','FOLLOWUP_MESSAGE','FILE_MESSAGE','CANCELLATION','CUSTOM'].map(x=>`<option>${x}</option>`).join('')}</select><button data-act="start">Start</button><button data-act="pause">Pause</button><button data-act="stop">Stop</button><button data-act="clear">Clear</button><button data-act="mark">Mark action</button><button data-act="settings">Settings</button></div><div class="tabs">${tabs.map(t=>`<button class="tab" data-tab="${t}">${t}</button>`).join('')}</div><div id="body"></div></div>`;document.documentElement.appendChild(host);const $=q=>shadow.querySelector(q);const p={$,tab:'Overview'};state.ui=p;
    let drag=null;$('#head').addEventListener('pointerdown',e=>{if(e.target.tagName==='BUTTON')return;drag={x:e.clientX,y:e.clientY,l:host.offsetLeft,t:host.offsetTop};host.style.right='auto';host.setPointerCapture&&host.setPointerCapture(e.pointerId)});shadow.addEventListener('pointermove',e=>{if(!drag)return;host.style.left=(drag.l+e.clientX-drag.x)+'px';host.style.top=(drag.t+e.clientY-drag.y)+'px'});shadow.addEventListener('pointerup',()=>drag=null);
    shadow.addEventListener('click',e=>{const b=e.target,act=b.dataset.act;if(b.dataset.tab){p.tab=b.dataset.tab;render();return}if(act==='start'){state.recording=true;state.paused=false;begin($('#scenario').value)}if(act==='pause'){state.paused=!state.paused;b.textContent=state.paused?'Resume':'Pause';render()}if(act==='stop'){end();state.recording=false;render()}if(act==='clear'){state.ops=[];state.streams=[];state.files=[];state.markers=[];state.scenarios=[];state.endpoints.clear();render()}if(act==='mark'){mark((state.current&&state.current.label||$('#scenario').value)+'_ACTION');render()}if(act==='settings'){if(!state.config.synthetic&&confirm('Enable capture of explicitly marked synthetic test payloads only?'))state.config.synthetic=true;else if(state.config.synthetic)state.config.synthetic=false;alert('Synthetic test payload capture: '+(state.config.synthetic?'ON':'OFF'));render()}if(act==='inspect')inspectStorage();if(act==='frontend')scanFrontend();if(act==='validate'){const v=validate(data('full'));alert(v.ok?'Redaction validation passed.':'EXPORT BLOCKED.')}if(act==='summary')download(`deepseek_observer_summary_${Date.now()}.json`,data('summary'));if(act==='full')download(`deepseek_observer_evidence_${Date.now()}.json`,data('full'));if(act==='zip'){const full=data('full');if(!validate(full).ok){alert('EXPORT BLOCKED.');return}const files={'summary.json':data('summary'),'endpoint_inventory.json':full.endpoint_inventory,'streams.json':full.streams||[],'storage.json':full.storage_summary||{},'frontend.json':full.frontend_resource_summary||[],'scenarios.json':full.scenario_summary||[],'README.txt':'Sanitized local-only passive observation package. No cookies, credentials, private message bodies, file contents, or bundles included.'};const a=document.createElement('a');a.href=URL.createObjectURL(zip(files));a.download=`deepseek_observer_package_${Date.now()}.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}if(act==='min')$('#p').classList.toggle('min');if(act==='close'){host.remove();state.ui=null}});render();};
  const start=()=>{install();document.addEventListener('change',recordFiles,true);document.addEventListener('drop',recordFiles,true);scanFrontend();inspectStorage();const wait=()=>{if(document.documentElement){ui();return}requestAnimationFrame(wait)};wait();state.timer=setInterval(()=>{if(state.ui)render()},200);};
  const reset=()=>{if(state.originals.fetch)window.fetch=state.originals.fetch;if(state.originals.X){const X=state.originals.X;X.prototype.open=state.originals.xopen;X.prototype.send=state.originals.xsend;X.prototype.setRequestHeader=state.originals.xset}if(state.originals.EventSource)window.EventSource=state.originals.EventSource;if(state.originals.WebSocket)window.WebSocket=state.originals.WebSocket;document.removeEventListener('change',recordFiles,true);document.removeEventListener('drop',recordFiles,true);clearInterval(state.timer);if(state.ui){try{state.ui.$('#p').parentNode.host.remove()}catch(_){}}delete globalThis.__DeepSeekObserverInstalled;delete globalThis.DeepSeekObserver};
  const selfTest=()=>{const r={events:[],completion_indicator:'UNKNOWN'},started=performance.now();parseSSE('event: test\ndata: {"safe":true}\n\ndata: [DONE]\n\n',r,started);return {status:'PASS',sse_parser_events:r.events.length,completion:r.completion_indicator,redaction:validate(redact({token:'example',safe:'ok'})).ok,network_activity_created:false};};
  globalThis.DeepSeekObserver={start:()=>{state.recording=true;state.paused=false;render()},pause:()=>{state.paused=true;render()},resume:()=>{state.paused=false;state.recording=true;render()},stop:()=>{state.recording=false;end();render()},clear:()=>{state.ops=[];state.streams=[];state.files=[];state.endpoints.clear();render()},mark,begin,end,inspectStorage,scanFrontend,summary,status:()=>({recording:state.recording,paused:state.paused,local_only:true}),config:o=>{if(o&&typeof o==='object'&&'synthetic'in o)state.config.synthetic=!!o.synthetic;return {...state.config}},export:()=>data('full'),selfTest,reset,help:()=>console.log('Passive local observer: use panel controls or DeepSeekObserver.begin(label), mark(label), end(), export(), selfTest(), reset().')};
  start();
})();
