/* Phase 5 passive XHR SSE metadata observer. Local only; no requests, replay, headers, or raw payload export. */
(() => {
  'use strict';
  if (globalThis.DeepSeekPhase5StreamObserver) { console.warn('[DS-P5-STREAM] Already installed.'); return; }
  const MAX_EVENTS=100, MAX_DELTA=65536, MAX_DEPTH=4, sensitive=/(token|cookie|authorization|csrf|xsrf|session|secret|password|api[_-]?key|credential)/i;
  const state={running:true,records:[],originals:{},installed_at:new Date().toISOString()};
  const safeURL=x=>{try{const u=new URL(x,location.href);return{origin:u.origin,path:u.pathname}}catch(_){return{origin:'UNKNOWN',path:'UNKNOWN'}}};
  const shape=(v,d=0)=>{if(d>MAX_DEPTH)return{type:'truncated_depth'};if(v===null)return{type:'null'};if(Array.isArray(v))return{type:'array',length:v.length,items:v.length?shape(v[0],d+1):{type:'unknown'}};if(typeof v!=='object')return{type:typeof v,length:typeof v==='string'?v.length:undefined};const keys={};Object.keys(v).slice(0,100).forEach(k=>keys[sensitive.test(k)?'<REDACTED_FIELD>':k]=sensitive.test(k)?{type:'<REDACTED>'}:shape(v[k],d+1));return{type:'object',keys}};
  const X=XMLHttpRequest, open=X.prototype.open, send=X.prototype.send; state.originals={open,send};
  X.prototype.open=function(method,url){this.__dsP5={method:String(method||'GET').toUpperCase(),url:safeURL(url),seen:0,record:null};return open.apply(this,arguments)};
  X.prototype.send=function(){const m=this.__dsP5||{method:'UNKNOWN',url:{origin:'UNKNOWN',path:'UNKNOWN'},seen:0,record:null};const start=performance.now();
    const progress=()=>{if(!state.running)return;let text;try{text=this.responseText}catch(_){if(m.record)m.record.access='NOT_ACCESSIBLE';return}if(typeof text!=='string'||text.length<=m.seen)return;const delta=text.slice(m.seen,Math.min(text.length,m.seen+MAX_DELTA));m.seen=text.length;
      if(!m.record){let ct='UNKNOWN';try{ct=this.getResponseHeader('content-type')||ct}catch(_){}m.record={status:'OBSERVED',timestamp:new Date().toISOString(),method:m.method,origin:m.url.origin,path:m.url.path,http_status:this.status||null,content_type:ct,transport:'xhr-progress',stream_start_ms:Math.round(performance.now()-start),stream_end_ms:null,duration_ms:null,observable_chunks:0,chunk_sizes:[],framing:'UNKNOWN',events:[],completion_indicator:'UNKNOWN',error_indicator:'UNKNOWN',raw_payloads_stored:false};state.records.push(m.record)}
      const r=m.record;r.observable_chunks++;r.chunk_sizes.push(delta.length);if(/text\/event-stream/i.test(r.content_type)||/(^|\n)(event|data):/m.test(delta))r.framing='SSE_LIKE_OBSERVED';
      delta.split(/\r?\n\r?\n/).slice(0,30).forEach(block=>{if(r.events.length>=MAX_EVENTS)return;const eventLine=block.split(/\r?\n/).find(x=>x.startsWith('event:'));const data=block.split(/\r?\n/).filter(x=>x.startsWith('data:')).map(x=>x.slice(5).trim()).join('\n');if(!data)return;if(data==='[DONE]'){r.completion_indicator='data_DONE';return}let s;try{s=shape(JSON.parse(data))}catch(_){s={type:'text',length:data.length}}r.events.push({event_index:r.events.length+1,event_type:eventLine?eventLine.slice(6).trim():'UNKNOWN',data_type:s.type,schema:s,timing_ms:Math.round(performance.now()-start)})});
    };
    this.addEventListener('progress',progress);this.addEventListener('abort',()=>{if(m.record)m.record.error_indicator='xhr_abort'});this.addEventListener('error',()=>{if(m.record)m.record.error_indicator='xhr_error'});this.addEventListener('loadend',()=>{if(m.record){m.record.stream_end_ms=Math.round(performance.now()-start);m.record.duration_ms=m.record.stream_end_ms;if(m.record.completion_indicator==='UNKNOWN')m.record.completion_indicator='xhr_loadend'}});return send.apply(this,arguments)};
  globalThis.DeepSeekPhase5StreamObserver={status:()=>({running:state.running,records:state.records.length,installed_at:state.installed_at}),pause:()=>state.running=false,resume:()=>state.running=true,clear:()=>state.records=[],export:()=>JSON.parse(JSON.stringify({metadata:{local_only:true,raw_payloads_stored:false},stream_observations:state.records})),reset:()=>{X.prototype.open=open;X.prototype.send=send;delete globalThis.DeepSeekPhase5StreamObserver}};
  console.log('[DS-P5-STREAM] Running. Future XHR progress only; original requests/responses are unchanged.');
})();
